package org.askil.eshift.ui.main;

import org.askil.eshift.user.User;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.ComponentContainer;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class MainPage extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private Label label_1;

	@AutoGenerated
	private MenuBar mainMenu;


	private static final Logger LOG = LoggerFactory.getLogger(MainPage.class);

	private MenuBar.MenuItem adminMenuItem;
	private MenuBar.MenuItem userAdminMenuItem;
	private Panel mainContent;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		buildMainMenu();
		// TODO add user code here
	}



	@Override
	public void attach() {
		super.attach();

		User user = (User) getApplication().getUser();
		if ( user == null ){
			LOG.error("No user set.");
			return;
		}

		if ( !user.isAdmin() ){
			adminMenuItem.setVisible(false);
		} 
	}

	public void buildMainMenu(){
		adminMenuItem = mainMenu.addItem("Admin", null);
		userAdminMenuItem = adminMenuItem.addItem("User Admin", null);
	}

	public void setModel(MainPageModel model){

	}
	
	public void setUserAdminMenuCommand(MenuBar.Command command){
		userAdminMenuItem.setCommand(command);
	}

	public void setContent(ComponentContainer component){
		mainContent.setContent(component);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		
		
		// mainMenu
		mainMenu = new MenuBar();
		mainMenu.setImmediate(false);
		mainMenu.setWidth("100.0%");
		mainMenu.setHeight("-1px");
		mainLayout.addComponent(mainMenu);
		
		// mainContent
		mainContent = new Panel();
		mainContent.setWidth("100.0%");
		mainContent.setHeight("100.0%");
		mainLayout.addComponent(mainContent);
		
		return mainLayout;
	}

}
